# 服务器配置
server:
  port: 8899

#  操作版本号
version: 1.0.0

# spring 日志
logging:
  config: classpath:logback-spring.xml
  file:
    name: Volumes/eDrive/Logs/JavaLogs/pratise-demo/my.log
    path: /Volumes/eDrive/Logs/JavaLogs/pratise-demo
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger{10}) - %cyan(%msg%n)'
    # file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n'

# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pratise_demo?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    # Druid datasource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小
      initial-size: 5
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 获取连接时的最大等待时间
      max-wait: 60000
      # 一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 多久才进行一次检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置扩展插件：stat-监控统计，log4j-日志，wall-防火墙（防止SQL注入），去掉后，监控界面的sql无法统计
      filters: stat,wall
      # 检测连接是否有效的 SQL语句，为空时以下三个配置均无效
      validation-query: SELECT 1
      # 申请连接时执行validationQuery检测连接是否有效，默认true，开启后会降低性能
      test-on-borrow: true
      # 归还连接时执行validationQuery检测连接是否有效，默认false，开启后会降低性能
      test-on-return: true
      # 申请连接时如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效，默认false，建议开启，不影响性能
      test-while-idle: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      #      aop-patterns: com.springboot.servie.*
      # 是否开启 StatViewServlet
      stat-view-servlet:
        enabled: true
        # 访问监控页面 白名单，默认127.0.0.1
        allow: 127.0.0.1
        login-username: admin
        login-password: admin
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        url-pattern: '/*' #匹配路径
        enabled: true  #是否监控
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*' #排除路径
        session-stat-enable: true #是否监控

      # FilterStat
      filter:
        stat:
          # 是否开启 FilterStat，默认true
          enabled: true
          # 是否开启 慢SQL 记录，默认false
          log-slow-sql: true
          # 慢 SQL 的标准，默认 3000，单位：毫秒
          slow-sql-millis: 5000
          # 合并多个连接池的监控数据，默认false
          merge-sql: false
        #配置WallFilter (防火墙配置)
        wall:
          enabled: true                                                               #开启防火墙
          config:
            update-allow: true                                                        #允许更新操作
            drop-table-allow: false                                                   #禁止删表操作
            insert-allow:  true                                                       #允许插入操作
            delete-allow: true                                                        #删除数据操作
  # Redis配置
  redis:
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0 # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
    # 首先是配置文件，由于我们使用的lettuce客户端，所以配置的时候，在spring.redis下加上lettuce再加上pool来配置，具体如下；
    lettuce:
      pool:
        # 当池耗尽时，在引发异常之前连接分配可以阻塞的最长时间（使用负值表示没有限制） 默认 -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        #        max-wait: -1ms
        max-wait: 5000
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    # 连接超时时间
    timeout: 10000ms
  # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
  cache:
    type: redis

  # 热加载
  devtools:
    restart:
      additional-paths: src/main/java #额外新增的热加载目录
      enabled: true #热加载生效
      #exclude=WEB-INF/** #热加载排除目录

# 测试配置数据
stars:
  blog:
    name: stars's blog
    title: Spring Boot
    wholeTitle: ${stars.blog.name}--${stars.blog.title}

  #  通用Mapper
  #  mapper.enum-as-simple-type： 枚举按简单类型处理，如果有枚举字段则需要加上该配置才会做映射
  #  mapper.not-empty： 设置以后，会去判断 insert 和 update 中字符串类型 !=''

  #  分页插件
  #  pagehelper.reasonable： 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  #  support-methods-arguments： 支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。

#　分页插件配置
pagehelper:
  helper-dialect: mysql
  # 该参数设置为true时 , pageNum <= 0时查询第一页 , pageNum > pages(超过总数时) , 会查询最后一页
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 通用Mapper设置
mapper:
  mappers: com.stars.pratise.demo.base.Mapper,com.stars.pratise.demo.crud.Mappers
  #  mappers: com.stars.pratise.demo.base.Mapper
  # 设置 insert 和 update 中，是否判断字符串类型!=''
  not-empty: false
  # 主键自增回写方法,默认值MYSQL,详细说明请看文档
  identity: MYSQL
  # 枚举按简单类型处理
  enum-as-simple-type: true

# Mybatis配置
mybatis:
  # mapper-locations: classpath:*/*.xml
  mapper-locations: classpath:mybatis/mapper/*.xml,classpath*:mapper/*.xml
  # 多个配置可以使用英文逗号隔开
  type-aliases-package: com.stars.pratise.demo.entity,com.stars.pratise.demo.log.domain , com.stars.pratise.demo.system.dto,com.stars.pratise.demo.domain,com.stars.pratise.demo.model,com.stars.pratise.demo.core.model,com.stars.pratise.demo.system.dto
  property:
    order: BEFORE
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
